runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: mKhvHNP4t8INsTrBwQ77EiKyvXXSXWcCZ5Z2iVXKSzo=
  STORAGE_DIR: /tmp
    CACHE_DRIVER: database
      SESSION_DRIVER: database
      DB_HOST: localhost
      DB_DATABASE: cloudproject
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_SOCKET: "/cloudsql/YOUR_CLOUDSQL_CONNECTION_NAME"
    beta_settings:
      cloud_sql_instances: "YOUR_CLOUDSQL_CONNECTION_NAME"

